### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Zer0xFF** [TheGamesDB/TheGamesDBv2#12]
Listed in no particular order:

- [ ] API, add recently added API (I still think this will be abused as an update API)
- [ ] API, basic statistics dash board
- [ ] API, Update API endpoint needs to be revised to be more transparent with the changes
e.g: if an image is added/removed, the API doesnt provide image id, nor does it provide side (front back)
- [ ] game collection, allow the user to mark games as owned, completed, incomplete 
- [ ] game collection, game play time, allow the user to specify how long it took them to complete a game
- [ ] game collection, allow game sorting
- [ ] game collection, "Missing Info" (show the user games they have in their collection that are missing info)
- [ ] game collection, add api, requires use permission
- [ ] a way to detect accidental double  game submissions
- [ ] recently added pages support
- [ ] show contributors to game (done, UI needs improving?, add pagination and platform filter)
- [ ] report system (partially completed, needs improving)
- [ ] Add Game Hashes to Database, implementation done(not tested), require user UI
- [ ] lock games, some games have complete set of info, lock them so they can't be edited (or add edits into a queue that must be approved by mods)
- [ ] return games with greater than specific ID (could be useful for project that only poll specific platforms, and would periodically check for updates)
- [ ] link related games
- [ ] link same game across platform
- [ ] make platform addable/editable
- [ ] basic mod dash
- [ ] increase image limit and size limit
- [ ] sort genre by name

add new platform: Evercade handheld

**Comment by smidley** [comment]
Couple of ideas that we discussed on Discord - 

Possibly center the main menu items at the top of the page like this: https://media.discordapp.net/attachments/462405261680967690/548529868409667594/unknown.png?width=2160&height=102

Add a Dark Mode theme to the site, and enable users to easily toggle it on or off.

I think instead of having the box arts across the top, we should show something else, probably new fan art.  That way the images are "standard size" and won't look oddly cropped.  They should also be consolidated, so that if fan art is uploaded for the PC version and the Xbox version, it's only shown once because the game title is the same.  We could tell the site to only show new fan art that has been uploaded.  If there's no fan art, that game is skipped.

https://media.discordapp.net/attachments/462405261680967690/548527488456720390/unknown.png?width=2102&height=1170

**Comment by darklightindigo** [comment]
- [ ] ]PLATFORM ADDS[
Commodore CDTV
GP32
Leap TV
Mattel Aquarius
Neo Geo X
Plug-and-Play Unit
Spectravideo
Timex Sinclair 1000
V-smile

- [x] ]GENRE ADDS[
Board (for Board Games)
Educational
Family (for Family Games)
Party (for Party Games)
Productivity
Unofficial
Utility
Video?
Virtual Console

- [ ] ]NEW PAGES[
Add Genre
Add Platform

- [ ] Genre / Subgenre Classifications System
- [ ] Tagging System
